scan_timeout = 10
add_newline = true

[character]
format = "$symbol "
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 5
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_onlystyle) "
style = "bold cyan"

[username]
style_root = "bold red"
style_user = "bold yellow"
format = "[$user]($style)@"
show_always = false
disabled = false

[hostname]
ssh_only = true
trim_at = "."
format = "[$hostname]($style):"
style = "bold dimmed green"
disabled = false

[cmd_duration]
min_time = 1_000
show_milliseconds = false
format = "took [$duration]($style) "
style = "bold yellow"
disabled = false
show_notifications = false
min_time_to_notify = 45_000

[aws]
#format = 'on [$symbol($profile)(\($region\) )]($style)'
format = 'on [$symbol($profile)]($style) '
style = "bold fg:#ff9900"
symbol = "🅰 "
disabled = false

[gcloud]
#format = 'on [$symbol$account(@$domain)(\($project\))]($style)'
format = 'on [$symbol$active]($style) '
style = "bold fg:#4285f4"
symbol = "🅶 "
disabled = false

